spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: TheL@b2023
    url: jdbc:sqlserver://newnotesdb.database.windows.net;databaseName=NotesV2Database;encrypt=false;trustServerCertificate=true
    username: paulSanga
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs